Repository CartoDB/cartoframes, pull requests merged in 2018-06, with the labels that each got.

#382 Example context
  README.rst
  cartoframes/__version__.py
  cartoframes/analysis.py
  cartoframes/context.py
  cartoframes/examples.py
  cartoframes/utils.py
  docs/cartoframes.rst
  docs/index.rst
  examples/Basic Usage.ipynb
  examples/Data Observatory Usage.ipynb
  examples/Example Datasets.ipynb
  examples/Shapely, Geopandas, and Cartoframes.ipynb
  requirements.txt
  test/test_analysis.py
  test/test_context.py
  test/test_examples.py
Labels: examples

#432 documentation: updates to read_x format
  docs/guides/01-Quickstart.md
  docs/guides/02-Cartography.md
  docs/guides/03-Spatial-Analysis.md
  docs/guides/04-Data-Observatory.md
Labels: documentation, examples

#452 adds additional specificity for temp tables to avoid name collisions
  test/test_context.py
Labels: tests

#459 Release version 0.7.0
  NEWS.rst
  cartoframes/__version__.py
Labels: Release
