Repository CartoDB/cartoframes, pull requests merged in 2019-09, with the labels that each got.

#948 Helper parameter updates
  cartoframes/viz/helpers/cluster_size_layer.py
  cartoframes/viz/helpers/color_bins_layer.py
  cartoframes/viz/helpers/color_category_layer.py
  cartoframes/viz/helpers/color_continuous_layer.py
  cartoframes/viz/helpers/size_bins_layer.py
  cartoframes/viz/helpers/size_category_layer.py
  cartoframes/viz/helpers/size_continuous_layer.py
  test/viz/helpers/test_cluster_size_layer.py
  test/viz/helpers/test_color_bins_layer.py
  test/viz/helpers/test_color_category_layer.py
  test/viz/helpers/test_color_continuous_layer.py
Labels: Helpers, do-not-merge

#949 Feature/do discovery
  cartoframes/data/observatory/__init__.py
  cartoframes/data/observatory/catalog.py
  cartoframes/data/observatory/category.py
  cartoframes/data/observatory/country.py
  cartoframes/data/observatory/dataset.py
  cartoframes/data/observatory/geography.py
  cartoframes/data/observatory/repository/__init__.py
  cartoframes/data/observatory/repository/category_repo.py
  cartoframes/data/observatory/repository/country_repo.py
  cartoframes/data/observatory/repository/dataset_repo.py
  cartoframes/data/observatory/repository/geography_repo.py
  cartoframes/data/observatory/repository/repo_client.py
  cartoframes/data/observatory/repository/variable_repo.py
  cartoframes/data/observatory/variable.py
  do_metadata_key.py
  test/data/observatory/__init__.py
  test/data/observatory/examples.py
  test/data/observatory/repository/__init__.py
  test/data/observatory/repository/test_category_repo.py
  test/data/observatory/repository/test_country_repo.py
  test/data/observatory/repository/test_dataset_repo.py
  test/data/observatory/repository/test_geography_repo.py
  test/data/observatory/repository/test_variable_repo.py
  test/data/observatory/test_catalog.py
  test/data/observatory/test_category.py
  test/data/observatory/test_country.py
  test/data/observatory/test_dataset.py
  test/data/observatory/test_geography.py
  test/data/observatory/test_variable.py
Labels: discovery

#969 in upload, if creds are None, use default creds
  cartoframes/data/dataset/dataset.py
Labels: bug

#974 Fix column names in df upload v2
  cartoframes/data/dataset/registry/dataframe_dataset.py
  cartoframes/utils/columns.py
  test/data/dataset/test_dataset.py
  test/mocks/context_mock.py
  test/mocks/dataset_mock.py
  test/utils/test_columns.py
Labels: bug
