Repository CartoDB/cartoframes, pull requests merged in 2019-04, with the labels that each got.

#589 Delete table using DROP TABLE
  cartoframes/context.py
  cartoframes/datasets.py
  test/test_context.py
  test/test_dataset.py
Labels: do-not-merge

#586 Review CARTO VL Namespace & API
  cartoframes/assets/templates/vector/scripts/map.js.j2
  cartoframes/assets/vector.html
  cartoframes/carto_vl/__init__.py
  cartoframes/carto_vl/basemap/__init__.py
  cartoframes/carto_vl/basemap/basemaps.py
  cartoframes/carto_vl/layer/__init__.py
  cartoframes/carto_vl/layer/layer.py
  cartoframes/carto_vl/layer/local_layer.py
  cartoframes/carto_vl/layer/query_layer.py
  cartoframes/carto_vl/maps/__init__.py
  cartoframes/carto_vl/maps/map.py
  cartoframes/carto_vl/utils/__init__.py
  cartoframes/carto_vl/utils/defaults.py
  cartoframes/carto_vl/utils/html.py
  cartoframes/context.py
  cartoframes/contrib/vector.py
  examples/debug/carto_vl/animation/add_animation_controls.ipynb
  examples/debug/carto_vl/animation/add_background_feature_visibility.ipynb
  examples/debug/carto_vl/animation/animate_and_color_by_date.ipynb
  examples/debug/carto_vl/animation/animate_by_date_range.ipynb
  examples/debug/carto_vl/animation/animate_feature_width.ipynb
  examples/debug/carto_vl/animation/animate_filtered_features.ipynb
  examples/debug/carto_vl/animation/hold_features_on_fade_out.ipynb
  examples/debug/carto_vl/basemap/basic_layer.ipynb
  examples/debug/carto_vl/basic/basemap.ipynb
  examples/debug/carto_vl/basic/basic_layer.ipynb
  examples/debug/carto_vl/basic/viewport.ipynb
  examples/debug/carto_vl/interactivity/basic_interactivity.ipynb
  examples/debug/carto_vl/interactivity/basic_interactivity_list.ipynb
  examples/debug/carto_vl/local/local_example.ipynb
  examples/debug/carto_vl/sources/geojson_source.ipynb
  examples/debug/carto_vl/sources/geojson_source_without_context.ipynb
  examples/debug/carto_vl/sources/points.geojson
  examples/debug/carto_vl/sources/sql_source.ipynb
  examples/debug/carto_vl/style-guide.ipynb
  examples/debug/carto_vl/styling/color_category.ipynb
  examples/debug/carto_vl/styling/color_number.ipynb
  examples/debug/carto_vl/styling/color_palettes.ipynb
  examples/debug/carto_vl/styling/color_spaces.ipynb
  examples/debug/carto_vl/styling/draw_order.ipynb
  examples/debug/carto_vl/styling/external_image.ipynb
  examples/debug/carto_vl/styling/filter_styling.ipynb
  examples/debug/carto_vl/styling/multiple_images.ipynb
  examples/debug/carto_vl/styling/scaled_width.ipynb
  examples/debug/carto_vl/styling/single_image.ipynb
  examples/debug/carto_vl/styling/style_with_variables.ipynb
  examples/debug/carto_vl/styling/viewport_based_styling.ipynb
  examples/debug/carto_vl/styling/viz_string_test.ipynb
  examples/debug/carto_vl/styling/zoomrange.ipynb
  test/carto_vl/test_basemaps.py
  test/carto_vl/test_carto.py
  test/carto_vl/test_layers.py
  test/carto_vl/test_map.py
  test/carto_vl/utils.py
  test/test_contrib_vector.py
Labels: blocked

#620 Create default CARTO VL error template
  cartoframes/assets/templates/error/basic.html.j2
  cartoframes/assets/templates/error/parser.js.j2
  cartoframes/assets/templates/vector/basic.html.j2
  cartoframes/assets/templates/vector/scripts/map.js.j2
  cartoframes/carto_vl/utils/defaults.py
  cartoframes/carto_vl/utils/html.py
  examples/debug/carto_vl/error_capture.ipynb
Labels: Triple Integration 🔱
