Repository CartoDB/cartoframes, pull requests merged in 2019-06, with the labels that each got.

#716 Upgrade CARTO VL & mapbox-gl-ls references
  cartoframes/assets/templates/viz/basic.html.j2
  examples/debug/API/basemaps.ipynb
  examples/debug/API/complete.ipynb
  examples/debug/API/helpers.ipynb
  examples/debug/API/legend.ipynb
  examples/debug/API/popup.ipynb
  examples/debug/API/source-geojson.ipynb
  examples/debug/API/source.ipynb
  examples/debug/API/style.ipynb
  examples/debug/carto_vl/animation/add_background_feature_visibility.ipynb
  examples/debug/carto_vl/animation/animate_and_color_by_date.ipynb
  examples/debug/carto_vl/animation/animate_by_date_range.ipynb
  examples/debug/carto_vl/animation/animate_feature_width.ipynb
  examples/debug/carto_vl/animation/animate_filtered_features.ipynb
  examples/debug/carto_vl/animation/hold_features_on_fade_out.ipynb
  examples/debug/carto_vl/basemap/basic_layer.ipynb
  examples/debug/carto_vl/basic/basemap.ipynb
  examples/debug/carto_vl/basic/basic_layer.ipynb
  examples/debug/carto_vl/basic/viewport.ipynb
  examples/debug/carto_vl/error_capture.ipynb
  examples/debug/carto_vl/interactivity/basic_interactivity.ipynb
  examples/debug/carto_vl/interactivity/basic_interactivity_list.ipynb
  examples/debug/carto_vl/local/local_example.ipynb
  examples/debug/carto_vl/sources/Dataset.ipynb
  examples/debug/carto_vl/sources/GeoJSON.ipynb
  examples/debug/carto_vl/sources/SQL.ipynb
  examples/debug/carto_vl/style-guide.ipynb
  examples/debug/carto_vl/styling/color_category.ipynb
  examples/debug/carto_vl/styling/color_number.ipynb
  examples/debug/carto_vl/styling/color_palettes.ipynb
  examples/debug/carto_vl/styling/color_spaces.ipynb
  examples/debug/carto_vl/styling/draw_order.ipynb
  examples/debug/carto_vl/styling/external_image.ipynb
  examples/debug/carto_vl/styling/filter_styling.ipynb
  examples/debug/carto_vl/styling/multiple_images.ipynb
  examples/debug/carto_vl/styling/scaled_width.ipynb
  examples/debug/carto_vl/styling/single_image.ipynb
  examples/debug/carto_vl/styling/style_with_variables.ipynb
  examples/debug/carto_vl/styling/viewport_based_styling.ipynb
  examples/debug/carto_vl/styling/viz_string_test.ipynb
  examples/debug/carto_vl/styling/zoomrange.ipynb
Labels: 0.10, blocked

#766 Hotfix 0.10.1
  NEWS.rst
  README.rst
  cartoframes/__version__.py
  cartoframes/columns.py
  cartoframes/context.py
  cartoframes/dataset.py
  test/test_dataset.py
Labels: do-not-merge

#788 V1.x docs kuviz
  cartoframes/viz/map.py
  docs/index.rst
  docs/kuviz.rst
Labels: documentation

#777 v1.0.0b docs updates
  .readthedocs.yml
  README.rst
  cartoframes/auth/__init__.py
  cartoframes/data/__init__.py
  cartoframes/data/dataset.py
  cartoframes/viz/__init__.py
  cartoframes/viz/helpers/__init__.py
  cartoframes/viz/helpers/color_bins_layer.py
  cartoframes/viz/helpers/color_category_layer.py
  cartoframes/viz/helpers/color_continuous_layer.py
  cartoframes/viz/helpers/size_bins_layer.py
  cartoframes/viz/helpers/size_category_layer.py
  cartoframes/viz/helpers/size_continuous_layer.py
  cartoframes/viz/layer.py
  cartoframes/viz/legend.py
  cartoframes/viz/map.py
  cartoframes/viz/popup.py
  cartoframes/viz/source.py
  cartoframes/viz/style.py
  docs/batchjobstatus.rst
  docs/cartocontext.rst
  docs/cartoframes.rst
  docs/conf.py
  docs/data.rst
  docs/etl.rst
  docs/img/data-workflow.gif
  docs/img/read_demo.gif
  docs/index.rst
  docs/kuviz.rst
  docs/maps.rst
  docs/requirements.txt
Labels: documentation
