Repository CartoDB/cartoframes, pull requests merged in 2019-12, with the labels that each got.

#1315 Fix/do open data
  cartoframes/data/clients/bigquery_client.py
  cartoframes/data/observatory/catalog/dataset.py
  cartoframes/data/observatory/catalog/entity.py
  cartoframes/data/observatory/catalog/geography.py
  cartoframes/data/observatory/enrichment/enrichment_service.py
  tests/unit/data/observatory/catalog/mocks.py
Labels: blocked

#1321 Guides/copy edits
  docs/developer-center/examples/examples.json
  docs/developer-center/guides/01-Introduction.md
  docs/developer-center/guides/02-Installation.md
  docs/developer-center/guides/03-Authentication.md
  docs/developer-center/guides/04-Quickstart.md
  docs/developer-center/guides/05-Visualization.md
  docs/developer-center/guides/06-Data-discovery.md
  docs/developer-center/guides/07-Data-enrichment.md
  docs/developer-center/guides/08-Location-Data-Services.md
  examples/data_enrichment/enrichment_subscription_workflow.ipynb
  examples/data_enrichment/points_enrichment_private_dataset.ipynb
  examples/data_enrichment/points_enrichment_public_dataset.ipynb
  examples/data_enrichment/polygons_enrichment_private_dataset.ipynb
  examples/data_enrichment/polygons_enrichment_public_dataset.ipynb
  examples/data_services/geocoding_and_isolines.ipynb
  examples/data_services/geocoding_dataframe.ipynb
  examples/data_services/isochrones.ipynb
  examples/data_services/isodistances.ipynb
  examples/data_workflows/change_dataset_privacy.ipynb
  examples/data_workflows/create_cdf_from_csv.ipynb
  examples/data_workflows/create_cdf_from_geojson.ipynb
  examples/data_workflows/create_cdf_from_json.ipynb
  examples/data_workflows/create_cdf_from_query.ipynb
  examples/data_workflows/create_cdf_from_table.ipynb
  examples/data_workflows/upload_cdf_to_carto.ipynb
  examples/map_configuration/custom_viewport.ipynb
  examples/map_configuration/dark_theme.ipynb
Labels: documentation

#1351 Use ACS in the quickstart instead of AGS
  docs/developer-center/guides/04-Quickstart.md
Labels: documentation

#1366 Fix examples v1.0b7
  examples/layers/add_data_driven_style_layer.ipynb
  examples/layers/add_default_legend_layer.ipynb
  examples/layers/add_default_widget_layer.ipynb
  examples/layers/add_layer.ipynb
  examples/layers/add_multiple_layers.ipynb
  examples/layers/add_popup_click_layer.ipynb
  examples/layers/add_popup_hover_layer.ipynb
  examples/layers/add_style_layer.ipynb
  examples/legends/color_bins_legend.ipynb
  examples/legends/color_category_legend.ipynb
  examples/legends/color_continuous_legend.ipynb
  examples/legends/default_legend.ipynb
  examples/legends/legend_subtype.ipynb
  examples/legends/multiple_legends.ipynb
  examples/legends/opacity_in_legend.ipynb
  examples/legends/size_bins_legend.ipynb
  examples/legends/size_category_legend.ipynb
  examples/legends/size_continuous_legend.ipynb
  examples/legends/stroke_color_legend.ipynb
  examples/map_configuration/change_default_carto_basemap.ipynb
  examples/map_configuration/custom_viewport.ipynb
  examples/map_configuration/dark_theme.ipynb
  examples/map_configuration/solid_color_background.ipynb
  examples/map_layout/custom_layout.ipynb
  examples/map_layout/default_layout.ipynb
  examples/map_layout/interactive_layout.ipynb
  examples/map_layout/layout_titles.ipynb
  examples/map_layout/layout_viewport.ipynb
  examples/map_layout/save_image_layout.ipynb
  examples/popups/multiple_popup_events.ipynb
  examples/popups/popup_expressions.ipynb
  examples/popups/popup_on_click.ipynb
  examples/popups/popup_on_hover.ipynb
  examples/popups/popup_titles.ipynb
  examples/visualization_layers/animation_layer.ipynb
  examples/visualization_layers/cluster_size_layer.ipynb
  examples/visualization_layers/color_bins_layer.ipynb
  examples/visualization_layers/color_category_layer.ipynb
  examples/visualization_layers/color_continuous_layer.ipynb
  examples/visualization_layers/combine_visualization_layers.ipynb
  examples/visualization_layers/isolines_layer.ipynb
  examples/visualization_layers/size_bins_layer.ipynb
  examples/visualization_layers/size_category_layer.ipynb
  examples/visualization_layers/size_continuous_layer.ipynb
  examples/visualization_layers/visualize_your_data_guide_workflow.ipynb
  examples/widgets/animation_widget.ipynb
  examples/widgets/animation_widget_style_property.ipynb
  examples/widgets/category_widget.ipynb
  examples/widgets/default_widget.ipynb
  examples/widgets/formula_widget.ipynb
  examples/widgets/histogram_widget.ipynb
  examples/widgets/multiple_widgets.ipynb
  examples/widgets/time_series_widget.ipynb
Labels: bug, documentation, examples
